services:
  next:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    container_name: next
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - WATCHPACK_POLLING=true
    volumes:
      - ./apps/frontend:/app

  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    container_name: spring_boot
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    entrypoint: "java -jar /app/app.jar"
    networks:
      - spring-network

  postgres:
    image: postgres:10.3
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: bc8db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - spring-network

volumes:
  postgres_data:

networks:
  spring-network:
    external: true