services:
  next:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    container_name: frontend_container
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    volumes:
      - ./apps/frontend:/app

  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    container_name: backend_container
    ports:
      - "8000:8000"  
    volumes:
      - ./apps/backend:/app
    environment:
      - UVICORN_CMD=uvicorn main:app --host 0.0.0.0 --port 8000
    networks:
      - db-network

  postgres:
    image: postgres:10.3
    container_name: postgres_container
    environment:
      POSTGRES_USER: bc8admin
      POSTGRES_PASSWORD: bc8pass
      POSTGRES_DB: bc8db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - db-network

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"

volumes:
  postgres_data:

networks:
  db-network:
    external: true